# Generated by Django 4.2.1 on 2023-05-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Articulo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("cantidad", models.CharField(max_length=10, verbose_name="Cantidad")),
                (
                    "descripcion",
                    models.TextField(null=True, verbose_name="Descripcion"),
                ),
            ],
        ),
    ]
